
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - /home/patrick/data/uptime-kuma:/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.rule=Host(`kuma.devsec.ie`)
      - traefik.http.services.uptime-kuma.loadBalancer.server.port=9000
      - "traefik.docker.network=traefik_default"

networks:
  traefik_default:
    external: true
