services:
  semaphore:
    image: semaphoreui/semaphore:v2.10.22
    container_name: semaphore
    ports:
      - "3000:3000"
    environment:
      - SEMAPHORE_DB_DIALECT=bolt
      - SEMAPHORE_ADMIN=admin
      - SEMAPHORE_ADMIN_PASSWORD=
      - SEMAPHORE_ADMIN_NAME=Admin
      - SEMAPHORE_ADMIN_EMAIL=
      - TZ:Europe/Dublin
    volumes:
      - semaphore_data:/var/lib/semaphore
      - semaphore_config:/etc/semaphore
      - tmp_config:/tmp/semaphore

volumes:
  semaphore_data:
  semaphore_config:
  tmp_config: